config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :bought_lists

  resources :bought_cards

  devise_for :users

  root 'buy_lists#index'

  resources :buy_lists do
    member do
      post 'update_all_prices'
      post 'update_user_prices'
    end
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :cards, only: [:update, :index, :destroy]
      resources :buy_lists do
        get 'total_price', on: :member
      end
    end
  end

  mount Resque::Server.new, at: '/resque'

end

app/models/buy_list.rb
class BuyList < ActiveRecord::Base
  has_many :cards
  belongs_to :user

  validates :dolar, presence: true
end

app/controllers/api/v1/buy_lists_controller.rb
module Api
  module V1
    class BuyListsController < ApplicationController
      include ActionView::Helpers::NumberHelper

      before_action :set_buy_list, only: [:total_price]

      def total_price
        user_cards = @buy_list.cards.where(user: current_user)

        usd_price = 0
        user_cards.each do |card|
          usd_price += card.price * card.quantity
        end
        clp_price = usd_price * @buy_list.dolar

        render json: {
          usd_price: usd_price,
          clp_price: clp_price,
          usd_price_formatted: number_to_currency(usd_price),
          clp_price_formatted: number_to_currency(clp_price, locale: 'es-CL')
        }
      end

      private

      def set_buy_list
        @buy_list = BuyList.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def buy_list_params
        params.require(:buy_list).permit(:user_id, :requested, :order_date, :dolar)
      end
    end
  end
end

app/controllers/buy_lists_controller.rb
class BuyListsController < ApplicationController
  before_action :set_buy_list, only: [:show, :edit, :update, :destroy, :update_all_prices, :update_user_prices]
  before_action :authenticate_user!

  # GET /buy_lists
  # GET /buy_lists.json
  def index
    @active_buy_lists = BuyList.where(requested: false)
    @inactive_buy_lists = BuyList.where(requested: true)
  end

  # GET /buy_lists/1
  # GET /buy_lists/1.json
  def show
    users = User
      .joins(cards: :buy_list)
      .where('buy_lists.id = ?', @buy_list.id)
      .uniq

    @cards_by_user = []
    users.each do |user|
      @cards_by_user << user.cards.where(buy_list_id: @buy_list.id).order(:id)
    end

    @total_price = @buy_list.cards.sum('price * quantity')
  end

  # GET /buy_lists/new
  def new
    @buy_list = BuyList.new
  end

  # GET /buy_lists/1/edit
  def edit
  end

  # POST /buy_lists
  # POST /buy_lists.json
  def create
    @buy_list = BuyList.new(buy_list_params)
    @buy_list.user_id = current_user.id
    @buy_list.requested = false

    respond_to do |format|
      if @buy_list.save
        format.html { redirect_to @buy_list, notice: 'Buy list was successfully created.' }
        format.json { render :show, status: :created, location: @buy_list }
      else
        format.html { render :new }
        format.json { render json: @buy_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buy_lists/1
  # PATCH/PUT /buy_lists/1.json
  def update
    respond_to do |format|
      if @buy_list.update(buy_list_params)
        format.html { redirect_to @buy_list, notice: 'Buy list was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy_list }
      else
        format.html { render :edit }
        format.json { render json: @buy_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buy_lists/1
  # DELETE /buy_lists/1.json
  def destroy
    @buy_list.destroy
    respond_to do |format|
      format.html { redirect_to buy_lists_url, notice: 'Buy list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_all_prices
    cards = @buy_list.cards

    cards.each do |card|
      Resque.enqueue(UpdatePrices, card.id, card.link)
    end

    redirect_to @buy_list, notice: 'Los precios se están actualizando en estos momentos...'
  end

  def update_user_prices
    cards = @buy_list.cards.where(user: current_user)

    cards.each do |card|
      Resque.enqueue(UpdatePrices, card.id, card.link)
    end

    redirect_to new_buy_list_card_path(buy_list_id: @buy_list.id), notice: 'Los precios y stock se están actualizando...'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy_list
      @buy_list = BuyList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_list_params
      params.require(:buy_list).permit(:user_id, :requested, :order_date, :dolar)
    end
end

app/helpers/api/v1/buy_lists_helper.rb
module Api::V1::BuyListsHelper
end

app/helpers/buy_lists_helper.rb
module BuyListsHelper
end

app/views/buy_lists/_form.html.haml
.form-container
  = form_for @buy_list do |f|
    - if @buy_list.errors.any?
      #error_explanation
        %h2= "#{pluralize(@buy_list.errors.count, "error")} prohibited this buy_list from being saved:"
        %ul
          - @buy_list.errors.full_messages.each do |msg|
            %li= msg

    .form-group
      = f.label :dolar, 'Dolar (en CLP)'
      = f.number_field :dolar, class: 'form-control', placeholder: 'Ej: 630'
      %p.help-block Puedes cambiar el valor del dolar después.
    .form-group
      = f.label :order_date
      = f.date_field :order_date, class: 'form-control'
      %p.help-block Opcional. Puedes agregar la fecha del pedido después.

    = f.submit 'Crear', class: 'btn btn-default'

app/views/buy_lists/edit.html.haml
%h1 Editing buy_list

= render 'form'

= link_to 'Show', @buy_list
\|
= link_to 'Back', buy_lists_path

app/views/buy_lists/index.html.haml
.page-header
  %h1
    Pedidos activos
    - if @active_buy_lists.empty?
      = link_to icon('plus', 'Nuevo pedido'), new_buy_list_path, class: 'btn btn-default'

%table.table
  %thead
    %tr
      %th Nombre
      %th Creado por
      %th Fecha a realizar el pedido
  %tbody
    - @active_buy_lists.each do |buy_list|
      %tr
        %td
          = link_to "Pedido iniciado el #{buy_list.created_at.strftime('%d de %B del %Y')}", buy_list
        %td #{buy_list.user.name} #{buy_list.user.last_name}
        %td= buy_list.order_date.nil? ? 'No definida aún' : buy_list.order_date.strftime('%d de %B del %Y a las %H:%M')

.page-header
  %h1 Pedidos realizados

- if @inactive_buy_lists.empty?
  %p Aún no se han realizado pedidos :(
- else
  %table.table
    %thead
      %tr
        %th Fecha
        %th Creado por
        %th Fecha en que se realizó el pedido
    %tbody
      - @inactive_buy_lists.each do |buy_list|
        %tr
          %td Pedido del #{buy_list.created_at.strftime('%d de %B del %Y')}
          %td= buy_list.user.name
          %td= buy_list.order_date.nil? ? 'No definida aún' : buy_list.order_date.strftime('%d de %B del %Y a las %H:%M')

app/views/buy_lists/new.html.haml
= render 'form'

app/views/buy_lists/show.html.haml
- dolar = @buy_list.dolar

.col-md-12
  .page-header
    %h2
      Pedido a realizar el
      - if @buy_list.order_date.nil?
        %em fecha no definida aún
      - else
        #{@buy_list.order_date.strftime('%d de %B de %Y')}

      - if @buy_list.user.id == current_user.id
        = link_to icon('pencil-square-o', 'Editar dolar y fecha'), edit_buy_list_path(@buy_list), class: 'btn btn-info'
  %p
    Precio del dolar:
    %strong= number_to_currency(dolar, locale: 'es-CL')
  %p
    Precio total del pedido (USD):
    %strong= number_to_currency(@total_price)

  %p
    Precio total del pedido (CLP):
    %strong= number_to_currency(@total_price * dolar, locale: 'es-CL')

  = link_to icon('plus', 'Agrega tus cartas al pedido'), new_buy_list_card_path(params[:id]), class: 'btn btn-primary'

  - if @buy_list.user.id == current_user.id
    = form_tag "/buy_lists/#{@buy_list.id}/update_all_prices", class: 'pull-right' do |f|
      %button{class: 'btn btn-default', data: { disable_with: 'Actualizando datos...' } }
        = icon('refresh', 'Actualizar precios')

  %hr

  - @cards_by_user.each do |cards|
    - user = cards.take.user
    .well
      %h4= "#{user.name.capitalize} #{user.last_name.capitalize}"
      %table.table.table-condensed
        %thead
          %tr
            %th Nombre
            %th Cantidad
            %th Stock
            %th Condición
            %th Precio USD
            %th Precio CLP
        %tbody
          - price = 0
          - cards.each do |card|
            %tr{class: ("text-danger" if card.stock.nil?)}
              %td
                = link_to card.name, card.link, target: '_blank'
              %td= card.quantity
              %td
                - if card.stock.nil?
                  Sin stock
                - else
                  = card.stock
              %td
                - if card.condition.nil?
                  \-
                -else
                  = card.condition
              %td= number_to_currency(card.price * card.quantity)
              %td= number_to_currency(card.price * dolar * card.quantity, locale: 'es-CL')
            - price += card.price * card.quantity
          %tr
            %td
            %td
            %td
            %td
              %strong Total
            %td
              %strong
                = number_to_currency(price)
            %td
              %strong
                = number_to_currency(price * dolar, locale: 'es-CL')

      - if user.id == current_user.id
        = link_to icon('plus', 'Agregar más cartas'), new_buy_list_card_path(params[:id]), class: 'btn btn-default'