config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :bought_lists

  resources :bought_cards

  devise_for :users

  root 'buy_lists#index'

  resources :buy_lists do
    member do
      post 'update_all_prices'
      post 'update_user_prices'
    end
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :cards, only: [:update, :index, :destroy]
      resources :buy_lists do
        get 'total_price', on: :member
      end
    end
  end

  mount Resque::Server.new, at: '/resque'

end

app/models/bought_list.rb
class BoughtList < ActiveRecord::Base
  belongs_to :buy_list
  belongs_to :user
  has_many :bought_cards
  has_many :cards, through: :bought_cards

  def parse_raw_order
    # Parse Channelfireball checkout information in the format:
    # - 8x Bloodsoaked Champion, Khans of Tarkir\n   Condition: NM-Mint | Language: English, $11.92\n 
    # - 1x Mountain (242) - Zendikar Full Art (Lot of 20), «Wholesale Lots» Condition: Slightly Played, $17.99 
    
    #raw_order.split("\n").each_slice(2) do |card_info|
    raw_order.split((/\n\W-/)).each do |card_info|
      #todo
      basic_info = card_info.split(/\WCondition:\W/)[0].split(",")
      quantity = basic_info[0].slice!(/\W\d+x /).try(:scan, /\d/).join().try(:to_i)


      edition = basic_info.pop.try(:strip)
      card_name = basic_info.join(", ")

      more_info = card_info.split(/\WCondition:\W/)[1]
      if more_info.include? "|"
        # includes language
        raw_condition, raw_language_and_price  = more_info.split("|")
        raw_language, raw_price = raw_language_and_price.split(",")
      else
        # does not include language
        raw_condition, raw_price  = more_info.split(",")
      end

      condition = raw_condition.try(:strip)
      language = raw_language.gsub("Language:", "").try(:strip) if raw_language
      price = raw_price.gsub("$", "").try(:strip).try(:to_d)

      card = Card.find_by_name_and_buy_list_id(card_name, self.buy_list_id) || Card.create(
            name: card_name,
            condition: condition,
            quantity: quantity,
            price: (price/quantity).to_f,
            user: nil,
            buy_list_id: self.buy_list_id)

      #card_info
      BoughtCard.create(user:  card.user,
                        card: card,
                        condition: condition,
                        quantity: quantity,
                        edition: edition,
                        language: language,
                        usd_price: price/quantity,
                        bought_list: self)
    end
  end

  def count_all_cards
    bought_cards.map{|bought_card| bought_card.quantity}.reduce(:+)
  end

  def calculate_total_usd
    bought_cards.map{|bought_card| bought_card.total_usd}.reduce(:+).to_f
  end
end

app/controllers/bought_lists_controller.rb
class BoughtListsController < ApplicationController
  before_action :set_bought_list, only: [:show, :edit, :update, :destroy]

  # GET /bought_lists
  # GET /bought_lists.json
  def index
    @bought_lists = BoughtList.all
  end

  # GET /bought_lists/1
  # GET /bought_lists/1.json
  def show
  end

  # GET /bought_lists/new
  def new
    @bought_list = BoughtList.new
  end

  # GET /bought_lists/1/edit
  def edit
  end

  # POST /bought_lists
  # POST /bought_lists.json
  def create
    @bought_list = BoughtList.new(bought_list_params)

    respond_to do |format|
      if @bought_list.save
        format.html { redirect_to @bought_list, notice: 'Bought list was successfully created.' }
        format.json { render :show, status: :created, location: @bought_list }
      else
        format.html { render :new }
        format.json { render json: @bought_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bought_lists/1
  # PATCH/PUT /bought_lists/1.json
  def update
    respond_to do |format|
      if @bought_list.update(bought_list_params)
        format.html { redirect_to @bought_list, notice: 'Bought list was successfully updated.' }
        format.json { render :show, status: :ok, location: @bought_list }
      else
        format.html { render :edit }
        format.json { render json: @bought_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bought_lists/1
  # DELETE /bought_lists/1.json
  def destroy
    @bought_list.destroy
    respond_to do |format|
      format.html { redirect_to bought_lists_url, notice: 'Bought list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bought_list
      @bought_list = BoughtList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bought_list_params
      params.require(:bought_list).permit(:total_usd, :raw_order, :buy_list_id, :user_id)
    end
end

app/helpers/bought_lists_helper.rb
module BoughtListsHelper
end

app/views/bought_lists/_form.html.haml
= form_for @bought_list do |f|
  - if @bought_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bought_list.errors.count, "error")} prohibited this bought_list from being saved:"
      %ul
        - @bought_list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :total_usd
    = f.text_field :total_usd
  .field
    = f.label :raw_order
    = f.text_area :raw_order
  .field
    = f.label :buy_list
    = f.text_field :buy_list
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/bought_lists/edit.html.haml
%h1 Editing bought_list

= render 'form'

= link_to 'Show', @bought_list
\|
= link_to 'Back', bought_lists_path

app/views/bought_lists/index.html.haml
%h1 Listing bought_lists

%table
  %thead
    %tr
      %th Total usd
      %th Raw order
      %th Buy list
      %th User
      %th
      %th
      %th
      
  %tbody
    - @bought_lists.each do |bought_list|
      %tr
        %td= bought_list.total_usd
        %td= bought_list.raw_order
        %td= bought_list.buy_list
        %td= bought_list.user
        %td= link_to 'Show', bought_list
        %td= link_to 'Edit', edit_bought_list_path(bought_list)
        %td= link_to 'Destroy', bought_list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bought list', new_bought_list_path

app/views/bought_lists/new.html.haml
%h1 New bought_list

= render 'form'

= link_to 'Back', bought_lists_path

app/views/bought_lists/show.html.haml
%p#notice= notice

%p
  %b Total usd:
  = @bought_list.total_usd
%p
  %b Raw order:
  = @bought_list.raw_order
%p
  %b Buy list:
  = @bought_list.buy_list
%p
  %b User:
  = @bought_list.user

= link_to 'Edit', edit_bought_list_path(@bought_list)
\|
= link_to 'Back', bought_lists_path