config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :bought_lists

  resources :bought_cards

  devise_for :users

  root 'buy_lists#index'

  resources :buy_lists do
    member do
      post 'update_all_prices'
      post 'update_user_prices'
    end
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :cards, only: [:update, :index, :destroy]
      resources :buy_lists do
        get 'total_price', on: :member
      end
    end
  end

  mount Resque::Server.new, at: '/resque'

end

app/models/bought_card.rb
class BoughtCard < ActiveRecord::Base
  belongs_to :card
  belongs_to :user
  belongs_to :bought_list

  def total_usd
    usd_price * quantity
  end
end

app/controllers/bought_cards_controller.rb
class BoughtCardsController < ApplicationController
  before_action :set_bought_card, only: [:show, :edit, :update, :destroy]

  # GET /bought_cards
  # GET /bought_cards.json
  def index
    @bought_cards = BoughtCard.all
  end

  # GET /bought_cards/1
  # GET /bought_cards/1.json
  def show
  end

  # GET /bought_cards/new
  def new
    @bought_card = BoughtCard.new
  end

  # GET /bought_cards/1/edit
  def edit
  end

  # POST /bought_cards
  # POST /bought_cards.json
  def create
    @bought_card = BoughtCard.new(bought_card_params)

    respond_to do |format|
      if @bought_card.save
        format.html { redirect_to @bought_card, notice: 'Bought card was successfully created.' }
        format.json { render :show, status: :created, location: @bought_card }
      else
        format.html { render :new }
        format.json { render json: @bought_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bought_cards/1
  # PATCH/PUT /bought_cards/1.json
  def update
    respond_to do |format|
      if @bought_card.update(bought_card_params)
        format.html { redirect_to @bought_card, notice: 'Bought card was successfully updated.' }
        format.json { render :show, status: :ok, location: @bought_card }
      else
        format.html { render :edit }
        format.json { render json: @bought_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bought_cards/1
  # DELETE /bought_cards/1.json
  def destroy
    @bought_card.destroy
    respond_to do |format|
      format.html { redirect_to bought_cards_url, notice: 'Bought card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bought_card
      @bought_card = BoughtCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bought_card_params
      params.require(:bought_card).permit(:card_id, :usd_price, :user_id, :condition, :quantity, :bought_list_id)
    end
end

app/helpers/bought_cards_helper.rb
module BoughtCardsHelper
end

app/views/bought_cards/_form.html.haml
= form_for @bought_card do |f|
  - if @bought_card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bought_card.errors.count, "error")} prohibited this bought_card from being saved:"
      %ul
        - @bought_card.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :card
    = f.text_field :card
  .field
    = f.label :usd_price
    = f.text_field :usd_price
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :condition
    = f.text_field :condition
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :bought_list
    = f.text_field :bought_list
  .actions
    = f.submit 'Save'

app/views/bought_cards/edit.html.haml
%h1 Editing bought_card

= render 'form'

= link_to 'Show', @bought_card
\|
= link_to 'Back', bought_cards_path

app/views/bought_cards/index.html.haml
%h1 Listing bought_cards

%table
  %thead
    %tr
      %th Card
      %th Usd price
      %th User
      %th Condition
      %th Quantity
      %th Bought list
      %th
      %th
      %th
      
  %tbody
    - @bought_cards.each do |bought_card|
      %tr
        %td= bought_card.card
        %td= bought_card.usd_price
        %td= bought_card.user
        %td= bought_card.condition
        %td= bought_card.quantity
        %td= bought_card.bought_list
        %td= link_to 'Show', bought_card
        %td= link_to 'Edit', edit_bought_card_path(bought_card)
        %td= link_to 'Destroy', bought_card, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Bought card', new_bought_card_path

app/views/bought_cards/new.html.haml
%h1 New bought_card

= render 'form'

= link_to 'Back', bought_cards_path

app/views/bought_cards/show.html.haml
%p#notice= notice

%p
  %b Card:
  = @bought_card.card
%p
  %b Usd price:
  = @bought_card.usd_price
%p
  %b User:
  = @bought_card.user
%p
  %b Condition:
  = @bought_card.condition
%p
  %b Quantity:
  = @bought_card.quantity
%p
  %b Bought list:
  = @bought_card.bought_list

= link_to 'Edit', edit_bought_card_path(@bought_card)
\|
= link_to 'Back', bought_cards_path