config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  resources :bought_lists

  resources :bought_cards

  devise_for :users

  root 'buy_lists#index'

  resources :buy_lists do
    member do
      post 'update_all_prices'
      post 'update_user_prices'
    end
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :cards, only: [:update, :index, :destroy]
      resources :buy_lists do
        get 'total_price', on: :member
      end
    end
  end

  mount Resque::Server.new, at: '/resque'

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :buy_list
  belongs_to :user
  has_many :bought_cards, dependent: :destroy
end

app/controllers/api/v1/cards_controller.rb
module Api
  module V1
    class CardsController < ApplicationController
      protect_from_forgery with: :null_session
      before_action :set_card, only: [:update, :destroy]

      def index
        buy_list = BuyList.find card_params[:buy_list_id]

        cards = buy_list.cards.where(user: current_user).order(:id).decorate

        render json: cards, methods: [:usd_price_formatted, :total_usd_price_formatted, :clp_price_formatted, :total_clp_price_formatted]
      end

      def update
        if @card.update(card_params)
          render json: @card
        else
          render json: @card.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @card.destroy

        head :no_content
      end

      private

      def set_card
        @card = Card.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def card_params
        params.require(:card).permit(:name, :price, :link, :user_id, :quantity, :buy_list_id)
      end
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /cards
  # GET /cards.json
  def index
    buy_list = BuyList.find params[:buy_list_id]
    @cards = buy_list.cards.order(:id)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    buy_list = BuyList.find params[:buy_list_id]
    @card = buy_list.cards.build

    @cards = Card.all
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    require 'nokogiri'
    require 'open-uri'

    buy_list = BuyList.find params[:buy_list_id]

    cards = card_params[:link].split("\n")

    cards.each do |link|
      @card = buy_list.cards.build(link: link)

      doc = Nokogiri::HTML(open(link))

      @card.name = doc.at_css('h1.pagetitle').text
      @card.user = current_user
      @card.quantity = 0
      @card.price = 0

      cards_without_stock = []

      if doc.css('h2.product-heading')[2].text != 'Currently Out Of Stock'
        @card.condition = doc.at_css('table.prod-variants .even td').text
        @card.price = doc.at_css('table.prod-variants .even td .price').text[/[0-9\.]+/]
        @card.stock = doc.at_css('table.prod-variants .even td .qty').text[/[0-9\.]+/]
        @card.quantity = 1
      else
        cards_without_stock << @card.name
      end

      @card.save
    end

    respond_to do |format|
      format.html { redirect_to new_buy_list_card_url, notice: 'Tus cartas se ha agreado con éxito' }
      format.json { render :show, status: :created, location: @card }
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :price, :link, :user_id)
    end
end

app/helpers/api/v1/cards_helper.rb
module Api::V1::CardsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.haml
= form_for @card do |f|
  - if @card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      %ul
        - @card.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :user_id
    = f.number_field :user_id
  .actions
    = f.submit 'Save'


%table.table
  %thead
    %tr
      %th Nombre
      %th Precio
      %th Condición
  %tbody
    - @cards.each do |card|
      %tr
        %td= card.name
        %td= card.price
        %td= card.condition

app/views/cards/edit.html.haml
%h1 Editing card

= render 'form'

= link_to 'Show', @card
\|
= link_to 'Back', cards_path

app/views/cards/index.html.haml
%h1 Listing cards

%table
  %thead
    %tr
      %th Name
      %th Price
      %th Link
      %th User
      %th
      %th
      %th

  %tbody
    - @cards.each do |card|
      %tr
        %td= card.name
        %td= card.price
        %td= card.link
        %td= card.user_id
        %td= link_to 'Show', buy_list_card_path(params[:buy_list_id], card.id)
        / %td= link_to 'Edit', edit_card_path(card)
        %td= link_to 'Destroy', buy_list_card_path(params[:buy_list_id], card.id), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Card', new_buy_list_card_path

app/views/cards/new.html.haml
= javascript_include_tag 'cards'

- dolar = @card.buy_list.dolar
- buy_list = @card.buy_list.id

.col-md-12
  = link_to '< Volver al pedido', @card.buy_list
  .form-container.link
    = form_for [@card.buy_list, @card], html: { class: 'form-inline' } do |f|
      - if @card.errors.any?
        #error_explanation
          %h2= "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
          %ul
            - @card.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.text_area :link, class: 'form-control link', placeholder: 'Link'
      = f.submit 'Obtener', class: 'btn btn-default', data: { disable_with: 'Obteniendo datos...'}

      %p.help-block (Ej: http://store.channelfireball.com/catalog/magic_singles-khans_of_tarkir_block-fate_reforged/break_through_the_line/431843)
  %hr

  = form_tag "/buy_lists/#{buy_list}/update_user_prices", class: 'pull-right' do |f|
    %button{class: 'btn btn-default', data: { disable_with: 'Actualizando datos...' } }
      = icon('refresh', 'Actualizar precios')


  %dl.dl-horizontal
    %dt Precio Total (USD)
    %dd.total-usd-price
    %dt Precio Total (CLP)
    %dd.total-clp-price

  %hr

  #buy-list{ data: { id: buy_list } }

app/views/cards/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @card.name
%p
  %b Price:
  = @card.price
%p
  %b Link:
  = @card.link
%p
  %b User:
  = @card.user_id

= link_to 'Edit', edit_card_path(@card)
\|
= link_to 'Back', cards_path